apiVersion: v1
kind: Service
metadata:
  name: researchflow
  namespace: researchflow
  labels:
    app: researchflow
spec:
  type: ClusterIP
  selector:
    app: researchflow
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
